parameter = [
    {name = "dev.frontend.catalogue_url" ,value = "http://catalogue-dev.unlockers.online:8080/"},
    {name = "dev.frontend.cart_url" ,value = "http://cart-dev.unlockers.online:8080/"},
    {name = "dev.frontend.user_url" ,value = "http://user-dev.unlockers.online:8080/"},
    {name = "dev.frontend.shipping_url" ,value = "http://shipping-dev.unlockers.online:8080/"},
    {name = "dev.frontend.payment_url" ,value = "http://payment-dev.unlockers.online:8080/"},
    {name = "dev.catalogue.mongo_repo_url" ,value = "mongodb-dev.unlockers.online"},
    {name = "dev.catalogue.mongo" ,value = "MONGO=true"},
    {name = "dev.catalogue.mongo_url" ,value = "mongodb://mongodb-dev.unlockers.online:27017/catalogue"},
    {name = "dev.user.mongo" ,value = "MONGO=true"},
    {name = "dev.user.redis_host" ,value = "redis-dev.unlockers.online"},
    {name = "dev.user.mongo_url" ,value = "redis-dev.unlockers.online"},
    {name = "dev.cart.redis_url" ,value = "redis-dev.unlockers.online"},
    {name = "dev.cart.catalogue_url" ,value = "catalogue-dev.unlockers.online"},
    {name = "dev.cart.catalogue_port" ,value = "8080"},
    {name = "dev.mysql_url" ,value = "mysql-dev.unlockers.online"},
    {name = "dev.cart_url" ,value = "cart-dev.unlockers.online:8080"},
    {name = "dev.cart_url" ,value = "dev.unlockers.online:8080"},
    {name = "dev.mysql_url_schema" ,value = "mysql-dev.unlockers.online"},
    {name = "mysql_root_passwd" ,value = "RoboShop@1"}
] 
